# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('lena-lte-comparison', ['nr','flow-monitor'])
    obj.source = 'radio-network-parameters-helper.cc lena-lte-comparison.cc'
