NR SL UE architectures
======================

The architecture of the radio protocol stack model of the NR UE is represented
in the figures :ref:`fig-nr-sl-arch-ue-data-plane` and
:ref:`fig-nr-sl-arch-ue-ctrl-plane` which highlight respectively the data plane and
the control plane.

.. _fig-nr-sl-arch-ue-data-plane:
 
.. figure:: figures/nr-sl-arch-ue-data-plane.*
   :align: center

   Radio protocol stack architecture for the NR UE on the data plane of NR
   Sidelink


.. _fig-nr-sl-arch-ue-ctrl-plane:

.. figure:: figures/nr-sl-arch-ue-ctrl-plane.*
   :align: center

   Radio protocol stack architecture for the NR UE on the control plane of
   NR Sidelink
